---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: currency-exchange
 labels:
  app: currency-exchange
spec:
 replicas: 1
 selector:
  matchLabels:
   app: currency-exchange
 template:
  metadata: 
   labels:
    app: currency-exchange
  spec:
   containers:
   - name: currency-exchange
     image: justinmgeorgedocker/currexchange:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
spec:
  type: LoadBalancer
  selector:
    app: currency-exchange
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080